version: '3.1'
services:
  document_store:
    container_name: routesim.mongo
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hackerman
  document_store_interface:
    container_name: routesim.mongo-express
    image: mongo-express
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: routesim.mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hackerman
      ME_CONFIG_OPTIONS_EDITORTHEME: abcdef